# game constants

UPDATE_PERIOD = 0.05

WORLD_CIRCLE_RADIUS = 50
WORLD_CIRCLE_INNER_RADIUS = 35
WORLD_PASSAGEWAY_MARGIN = 15
WORLD_SIDE_WIDTH = 20
WORLD_CENTER_HALF_WIDTH = 15
WORLD_HALF_SIZE_X = WORLD_CIRCLE_RADIUS + WORLD_SIDE_WIDTH
WORLD_HALF_SIZE_Y = WORLD_CIRCLE_RADIUS
WORLD_PASSAGEWAY_HALF_WIDTH = WORLD_HALF_SIZE_Y - WORLD_PASSAGEWAY_MARGIN

MIN_DIST_TO_NOTIFY = 0.04
MIN_DELTA_VELOICTY_TO_NOTIFY = 0.001

STUNNED_DURATION = 1.

BALL_DROP_DIST = 0.1
BALL_DROP_VELOCITY = 20
