# game constants

UPDATE_PERIOD = 0.05

WORLD_CIRCLE_RADIUS = 50
WORLD_PASSAGEWAY_MARGIN = 15
WORLD_SIDE_WIDTH = 20
WORLD_HALF_SIZE_X = WORLD_CIRCLE_RADIUS + WORLD_SIDE_WIDTH
WORLD_HALF_SIZE_Y = WORLD_CIRCLE_RADIUS
WORLD_PASSAGEWAY_HALF_WIDTH = WORLD_HALF_SIZE_Y - WORLD_PASSAGEWAY_MARGIN

TIME_BETWEEN_FIRE = 1

DIST_TO_HIT = 20
