# game constants

UPDATE_PERIOD = 0.05

WORLD_CIRCLE_RADIUS = 50
WORLD_CIRCLE_INNER_RADIUS = 35
WORLD_PASSAGEWAY_MARGIN = 15
WORLD_SIDE_WIDTH = 20
WORLD_CENTER_HALF_WIDTH = 15
WORLD_HALF_SIZE_X = WORLD_CIRCLE_RADIUS + WORLD_SIDE_WIDTH
WORLD_HALF_SIZE_Y = WORLD_CIRCLE_RADIUS
WORLD_PASSAGEWAY_HALF_WIDTH = WORLD_HALF_SIZE_Y - WORLD_PASSAGEWAY_MARGIN

WORLD_EPSILON = 0.0001

MIN_DIST_TO_NOTIFY = 0.04
MIN_DELTA_VELOICTY_TO_NOTIFY = 0.001

MIN_VELOCITY = 0.05
DEINTERLACE_MARGIN = 0.05

STUNNED_DURATION = 1.

BALL_DROP_DIST = 3
BALL_DROP_VELOCITY = 20

BULLET_SPAWN_DIST = 0.1
BULLET_VELOCITY = 10
WEAPON_COOLDOWN = 1

SLOWDOWN_FACTOR = 0.5
SLOWDOWN_DURATION = 6

BOX_RESPAWN_INTERVAL = 6
BOX_MAX_COUNT = 10

SCORING_PERIOD = 1
IN_RAINBOW_DELTA_POINTS = 6
GOALS_DELTA_POINTS = 50
GOAL_PLAYER_FACTOR = 2

FALL_IN_HOLE_POINT_LOSS = 20

MAX_PLAYER_COUNT = 16
